# BMOTD Configuration
language: "de"
always-middle: true

# MOTDs
motds:
  - line1: "<gradient:aqua:blue><b>EinfachBen</b></gradient>"
    line2: "<gray>Das ist ein Test"
  - line1: "<red>ðŸ”¥ PvP EVENT ðŸ”¥"
    line2: "<yellow>Join jetzt auf dem Server!"
  - line1: "<rainbow>BMOTD Plugin</rainbow>"
    line2: "<green>Jetzt mit Random-Rotation!"